name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: Ya hoo!  Thanks for the work item.  It's been labeled with 'triage' and will be updated if someone wants to take it on.
        pr-message: Boo ja!  Thanks for the PR.  A core member will look it over, enable the quality checks and then review the code.
